<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="img/argon/apple-icon.png">
  <link rel="icon" type="image/png" href="img/argon/favicon.png">
  <title>
    SWIPTM
  </title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

  <!-- <link href="css/fonts.googleapis.com_css_family=Open+Sans_300,400,600,700" rel="stylesheet" />-->

  <!--     Fonts and icons    
  <!-- Nucleo Icons -->
  <link href="css/argon/nucleo-icons.css" rel="stylesheet" />
  <link href="css/argon/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="javascript/argon/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="css/argon/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="css/argon/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
</head>
</html>