<div class="container-fluid, primary text-capitalize ">
    <h1 >empresas dadas de <tempnam class="text-danger">Baja</tempnam></h1>
</div>


<div id="personal">
    <div class="table-responsive">
            <div class="text-right mb-2">
                <button @click ="excel" class="btn btn-success">Excel</button>
                <button  @click = "pdf" class="btn btn-danger">PDF</button>
            </div>    
    
        <table id="data" class="table table-striped  table-borderless" style="width:100%">
            <thead class="table-dark text-capitalize">
                <tr>
                     
                    <th>Razón Social</th>
                    <th>RFC</th>
                    
                    <th> Opciones</th>
                </tr>    
            </thead>
            <tbody>
                <?php foreach ($empresas as $e): ?>
                <tr class="align-middle">
                    <td class="text-center"> 
                        <a href="show/<?= $e->id ?>" class="text-dark"> 
                        <?= $e->razon_social ?>
                    </a>
                </td>
                    <td><?= $e->rfc ?></td>
                    <td class="align-middle"> 
                    <center>
                        <a class="btn btn-primary" href="http://localhost/SWIPTM/default/public/empresas/reactivar/<?= $e->id ?>" role="button" onclick="">
                        <i class="bi bi-check-lg"></i>
                        </a>
                    </center>
                    </td>
                    <?php endforeach; ?>
                    
                </tr>
            </tbody>
        </table>
    </div>
    <script src="http://localhost/SWIPTM/default/public/javascript/tablas/personal/bajas.js"></script>
</div>
<div class="text-right mb-2">
    <a class="btn btn-danger" 
    href="http://localhost/SWIPTM/default/public/empresas"
    role="button" onclick="">
        <i class="bi bi-arrow-left-circle-fill"></i>
    </a>
</div>
