
<?php
// Establecer ruta global
$DOMINIO='http://localhost/SWIPTM/default/public';
?>

<div class="container-fluid, primary">
    <h1>Empresas </h1>
    
</div>
<div class="text-right mb-2">
<button id="download-csv"  class="btn btn-success" >Descarga Excel</button>
                                
<button id="download-pdf" class="btn btn-danger">Descarga PDF</button>
</div>
<!-- ========== Start Section ========== -->
<script src="<?= $DOMINIO ?>/javascript/tablas/empresas.js"></script>
<!-- ========== End Section ========== -->

<script>
    table = new Tabulator("empresas", {
    data: <?= json_encode($empresas) ?>,
    height:"311px",
    layout:"fitColumns",
    placeholder:"No Data Set",
    columns:[
    {title:"RAZON SOCIAL", field:"razon_social"}, //frozen column
    {title:"RFC", field:"rfc" },

    ],
});

document.getElementById("download-csv").addEventListener("click", function(){
    table.download("csv", "data.csv");
});

//trigger descarga pdf
document.getElementById("download-pdf").addEventListener("click", function(){
    table.download("pdf", "data.pdf", {
        orientation:"portrait", //set page orientation to portrait
        title:"", //add title to report
    });
});
</script>
<div id="empresas"> </div>


