<h1> <?= $empresa->razon_social ?></h1>

<div class="row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
      <div class="card-body text-capitalize text-center">
        <h5 class="card-title">
            RFC
        </h5>
        <p class="card-text">
        <?= $empresa->rfc ?>    
    </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body text-capitalize text-center">
        <h5 class="card-title">
            Razón Social
        </h5>
        <p class="card-text">
        <?= $empresa->razon_social ?>
        </p>
        
      </div>
    </div>
  </div>
</div>
<div class="text-right mb-2">
    <a class="btn btn-info" href="../../empresas/update/<?= $empresa->id ?>" role="button" onclick="">Editar</a>
    <a class="btn btn-danger" href="../../empresas/eliminar/ <?= $empresa->id ?> " role="button" onclick="">Eliminar</a>
    <a class="btn btn-warning" href="../../empresas<?php if($empresa->estatus == 0){
        echo('/bajas');
    }?>" role="button" onclick="">Regresar</a>

</div>  
