<?php
// Establecer ruta global
$DOMINIO='http://localhost/SWIPTM';
?>

<!-- Footer -->
<footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Sistema Integral Web &copy; Plasticos Técnicos Méxicanos 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
            