<?php
// Establecer ruta global
$DOMINIO='http://localhost/SWIPTM';
?>

<!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

<!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="<?= $DOMINIO ?>">
    <div class="sidebar-brand-icon rotate-n-0">
   
        <img src="<?= $DOMINIO ?>/img/ptml_logo.png" class="navbar-brand-img h-10" alt="main_logo"0>
      
    </div>
    <div class="sidebar-brand-text mx-3">SWIPTM</sup></div>
</a>

<!-- Divider -->
<hr class="sidebar-divider my-0">

<!-- Nav Item - Cursos -->
<li class="nav-item">
    <a class="nav-link" href="">
    <i class="bi bi-journal-bookmark-fill"></i>
        <span>Cursos</span></a>
</li>

<!-- Divider -->
<hr class="sidebar-divider">
<!-- Nav Item - Cursos -->
<li class="nav-item">
    <a class="nav-link" href="<?= $DOMINIO ?>/empresas">
    <i class="bi bi-building"></i>
        <span>Empresas
        </span></a>
</li>
<!-- Heading 
<div class="sidebar-heading">
    Interface
</div>
-->
<!-- Nav Item - Pages Collapse Menu 
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
        aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-fw fa-cog"></i>
        <span>Components</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="buttons.html">Buttons</a>
            <a class="collapse-item" href="cards.html">Cards</a>
        </div>
    </div>
</li>
-->

<!-- Nav Item - Cursos -->
<li class="nav-item">
    <a class="nav-link" href="<?= $DOMINIO ?>">
    <i class="bi bi-people"></i>
        <span>Personal
        </span></a>
</li>


<!-- Nav Item - Cursos -->
<li class="nav-item">
    <a class="nav-link" href="<?= $DOMINIO ?>/empresas">
    <i class="bi bi-person-vcard"></i>
        <span> Asesores
        </span></a>
</li>
<!-- Divider -->
<hr class="sidebar-divider">
<!-- Nav Item - Cursos -->
<li class="nav-item">
    <a class="nav-link" href="<?= $DOMINIO ?>/empresas">
    <i class="bi bi-file-earmark-bar-graph"></i>
        <span>Reportes
        </span></a>
</li>

</ul>
<!-- End of Sidebar -->
