<?php
// Establecer ruta global
$DOMINIO='http://localhost/SWIPTM';
?>

<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>SWIPTM</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php Tag::css('kumbia') ?>
  <?= Html::includeCss() ?>
  <link href="<?php echo($DOMINIO) ?>/libs/bootstrap-5.3.2-dist/css/boots.min.css" rel="stylesheet" >
  <link href="<?php echo($DOMINIO) ?>/libs/SB2/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" >
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<?php echo($DOMINIO) ?>/libs/SB2/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body id="page-top">
  
  <div id="wrapper">
    <?php View::partial('sidebar') ?>
    <div id="content-wrapper" class="d-flex flex-column">
    <?php View::partial('topbar') ?>
      <div class="container-fluid">
        <!-- Page Heading -->
        <?php View::content() ?>
        
      </div>
      <?php View::partial('footer') ?>
    </div>
  </div>
  <?php //View::partial('logut_model')?>

  <?php //View::content() ?>
  <?php //View::partial('kumbia/footer') ?>

 <!-- Bootstrap core JavaScript-->
 <script src="<?php echo($DOMINIO) ?>/libs/SB2/vendor/jquery/jquery.min.js"></script>
 <script src="<?php echo($DOMINIO) ?>/libs/bootstrap-5.3.2-dist/js/bootstrap.bundle.min.js"></script>   
 <script src="<?php echo($DOMINIO) ?>/libs/SB2/vendor/js/bootstrap.bundle.min.js"></script>
 <script src="<?php echo($DOMINIO) ?>/libs/vue/vue.global.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="<?php echo($DOMINIO) ?>/libs/SB2/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="<?php echo($DOMINIO) ?>/libs/SB2/js/sb-admin-2.min.js"></script>
</body>
</html>
