<?php View::content() ?>

<?= Form::open() ?>

<div class="card">
  <h5 class="card-header">RFC</h5>
  <div class="card-body">
    <h5 class="card-title"> Ingresa el RFC de la empresa</h5>
    <?= Form::text('empresa.rfc', array("class"=>"form-control", 'placeholder'=>'EJE89516524'))?>

    
  </div>
</div>

<div class="card">
  <h5 class="card-header">Razón Social</h5>
  <div class="card-body">
    <h5 class="card-title"> Ingresa el nombre completo de la empresa</h5>
<?= Form::text('empresa.razon_social', array('class' => 'form-control', 'placeholder'=>'EJEMPLO S.A. DE C.V.'))?>
</div>


<div class="text-right mb-2">
    <button type="submit" class="btn btn-success">Guardar</button>
    <a class="btn btn-danger" href="http://localhost/SWIPTM/empresas" role="button" onclick=""> Cancelar</a>
</div> 

<?// = Form::submit('Guardar') ?>
<?= Form::close() ?>
